export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_ERROR = "GET_USER_DATA_ERROR";

export const GET_COURSE_DATA = "GET_COURSE_DATA";
export const GET_COURSE_DATA_ERROR = "GET_COURSE_DATA_ERROR";

export const GET_MERGED_DATA = "GET_MERGED_DATA";
export const GET_MERGED_DATA_ERROR = "GET_MERGED_DATA_ERROR";

export const GET_CURRENCIES_DATA = "GET_CURRENCIES_DATA";
export const GET_CURRENCIES_DATA_ERROR = "GET_CURRENCIES_DATA_ERROR";

export const GET_FEES_DATA = "GET_FEES_DATA";
export const GET_FEES_DATA_ERROR = "GET_FEES_DATA_ERROR";

export const GET_CONVERTED_FEES_DATA = "GET_CONVERTED_FEES_DATA";
export const GET_CONVERTED_FEES_DATA_ERROR = "GET_CONVERTED_FEES_DATA_ERROR";

export const GET_FEES_SYMBOL = "GET_FEES_SYMBOL";
export const GET_FEES_SYMBOL_ERROR = "GET_FEES_SYMBOL_ERROR";