export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_ERROR = "GET_USER_DATA_ERROR";

export const GET_COURSE_DATA = "GET_COURSE_DATA";
export const GET_COURSE_DATA_ERROR = "GET_COURSE_DATA_ERROR";

export const GET_MERGED_DATA = "GET_MERGED_DATA";
export const GET_MERGED_DATA_ERROR = "GET_MERGED_DATA_ERROR";